#databases(mariadb)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/non_member_board
    username: root
    password:
  #JPA setting
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true # SQL ???

    hbm2ddl:

#logging
logging:
  level:
    com.memory.board: debug

